
package com.acn.manu.wsimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegionWSImpl", targetNamespace = "http://wsimpl.manu.acn.com/", wsdlLocation = "http://localhost:8080/DemoWebService-SimpleRegions/RegionWSImpl?WSDL")
public class RegionWSImpl_Service
    extends Service
{

    private final static URL REGIONWSIMPL_WSDL_LOCATION;
    private final static WebServiceException REGIONWSIMPL_EXCEPTION;
    private final static QName REGIONWSIMPL_QNAME = new QName("http://wsimpl.manu.acn.com/", "RegionWSImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DemoWebService-SimpleRegions/RegionWSImpl?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGIONWSIMPL_WSDL_LOCATION = url;
        REGIONWSIMPL_EXCEPTION = e;
    }

    public RegionWSImpl_Service() {
        super(__getWsdlLocation(), REGIONWSIMPL_QNAME);
    }

    public RegionWSImpl_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGIONWSIMPL_QNAME, features);
    }

    public RegionWSImpl_Service(URL wsdlLocation) {
        super(wsdlLocation, REGIONWSIMPL_QNAME);
    }

    public RegionWSImpl_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGIONWSIMPL_QNAME, features);
    }

    public RegionWSImpl_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegionWSImpl_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegionWSImpl
     */
    @WebEndpoint(name = "RegionWSImplPort")
    public RegionWSImpl getRegionWSImplPort() {
        return super.getPort(new QName("http://wsimpl.manu.acn.com/", "RegionWSImplPort"), RegionWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegionWSImpl
     */
    @WebEndpoint(name = "RegionWSImplPort")
    public RegionWSImpl getRegionWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsimpl.manu.acn.com/", "RegionWSImplPort"), RegionWSImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGIONWSIMPL_EXCEPTION!= null) {
            throw REGIONWSIMPL_EXCEPTION;
        }
        return REGIONWSIMPL_WSDL_LOCATION;
    }

}
